name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: function-app-demo

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    permissions: 
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Verify app builds, and that tests pass
      run: |
        dotnet restore
        dotnet build   --configuration Release --no-restore
        dotnet test    --configuration Release --no-restore
        dotnet publish --configuration Release --no-restore --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: function-app-demo
        path: ./publish

  build_and_push_image:
    runs-on: ubuntu-latest
    needs: build_and_test

    permissions: 
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push docker image
      id: build_image
      uses: DFE-Digital/github-actions/build-docker-image@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert image name to lowercase
      shell: pwsh
      run: echo "IMAGE_NAME_LOWER=$(('${{ steps.build_image.outputs.image }}').ToLower())" >> $GITHUB_ENV

  deploy_to_dev:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build_and_push_image

    environment: Development

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure (Dev)
      uses: Azure/functions-container-action@v1
      with:
        app-name: 'fa-docker-demo-dev'
        image: '${{ env.IMAGE_NAME_LOWER }}'

  deploy_to_test:
    runs-on: ubuntu-latest
    needs: deploy_to_dev
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    environment: Test

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure (Test)
      uses: Azure/functions-container-action@v1
      with:
        app-name: 'fa-docker-demo-test'
        image: '${{ env.IMAGE_NAME_LOWER }}'

  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: deploy_to_test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    environment: Production

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure (Prod)
      uses: Azure/functions-container-action@v1
      with:
        app-name: 'fa-docker-demo-prod'
        image: '${{ env.IMAGE_NAME_LOWER }}'

